name: Terraform-AWS

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    ######################################################
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1
    ######################################################
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.4.0
    ######################################################
    - name: Configure/Initialize/Validate Terraform
      run: terraform init && terraform validate && terraform plan
    ######################################################
    - name: Run Terraform
      run: terraform apply --auto-approve
    # ######################################################
    - name: Deleting everything
      run: terraform destroy --auto-approve
    ######################################################
    - name: Trigger CI/CD Workflow
      if: ${{ success() }}
      run: |
        curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.ACCESS_REPO_TOKEN }}" \
          https://api.github.com/repos/DolVladzio/provedcode_CI-CD/dispatches \
          -d '{"event_type": "trigger-ci-cd"}'
